# Generated by Django 3.0.5 on 2021-09-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviws',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reviws',
            name='titles',
        ),
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Reviws',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
