# Generated by Django 3.0.5 on 2021-09-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_auto_20210913_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.TextField(db_column='name', db_index=True, db_tablespace='name'),
        ),
    ]
