# Generated by Django 3.0.5 on 2021-09-14 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0005_auto_20210913_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre_title',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titlee', to='artwork.Genres'),
        ),
        migrations.AlterField(
            model_name='genre_title',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genree', to='artwork.Titles'),
        ),
    ]
