# Generated by Django 3.0.5 on 2021-09-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210913_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='user', max_length=254, unique=True, verbose_name='email adress'),
        ),
    ]
